
// Generated by Cadence Genus(TM) Synthesis Solution 16.13-s036_1
// Generated on: Jun 15 2023 12:28:26 BDT (Jun 15 2023 06:28:26 UTC)

// Verification Directory fv/TOP 

module csa_tree_gte_45_15_group_24(in_0, in_1, out_0);
  input [4:0] in_0, in_1;
  output out_0;
  wire [4:0] in_0, in_1;
  wire out_0;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI22X1 g156(.A0 (n_0), .A1 (n_4), .B0 (in_1[3]), .B1 (in_0[3]), .Y
       (out_0));
  OA21X1 g157(.A0 (in_1[2]), .A1 (in_0[2]), .B0 (n_3), .Y (n_4));
  OAI2BB1X1 g158(.A0N (in_1[2]), .A1N (in_0[2]), .B0 (n_2), .Y (n_3));
  OAI32X1 g159(.A0 (in_0[0]), .A1 (in_1[0]), .A2 (n_1), .B0 (in_1[1]),
       .B1 (in_0[1]), .Y (n_2));
  AND2X1 g160(.A (in_0[1]), .B (in_1[1]), .Y (n_1));
  AND2X1 g161(.A (in_0[3]), .B (in_1[3]), .Y (n_0));
endmodule

module csa_tree_gte_63_16_group_26(in_0, in_1, out_0);
  input [4:0] in_0, in_1;
  output out_0;
  wire [4:0] in_0, in_1;
  wire out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  AOI21X1 g170(.A0 (in_1[3]), .A1 (in_0[3]), .B0 (n_5), .Y (out_0));
  AOI2BB1X1 g171(.A0N (in_1[3]), .A1N (in_0[3]), .B0 (n_4), .Y (n_5));
  AOI31X1 g172(.A0 (in_1[0]), .A1 (in_0[0]), .A2 (n_1), .B0 (n_3), .Y
       (n_4));
  OA22X1 g173(.A0 (in_1[2]), .A1 (n_2), .B0 (in_0[2]), .B1 (n_0), .Y
       (n_3));
  AND2X1 g174(.A (n_0), .B (in_0[2]), .Y (n_2));
  OA22X1 g175(.A0 (in_1[1]), .A1 (in_0[1]), .B0 (in_1[2]), .B1
       (in_0[2]), .Y (n_1));
  AND2X1 g176(.A (in_0[1]), .B (in_1[1]), .Y (n_0));
endmodule

module ALU(A, B, S, Cin, clk, reset, F, Cout, DFT_sdi, DFT_sen);
  input [3:0] A, B;
  input [2:0] S;
  input Cin, clk, reset, DFT_sdi, DFT_sen;
  output [3:0] F;
  output Cout;
  wire [3:0] A, B;
  wire [2:0] S;
  wire Cin, clk, reset, DFT_sdi, DFT_sen;
  wire [3:0] F;
  wire Cout;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_132;
  wire n_133;
  csa_tree_gte_45_15_group_24 csa_tree_gte_45_15_groupi(.in_0
       ({UNCONNECTED_HIER_Z, A}), .in_1 ({UNCONNECTED_HIER_Z0, B}),
       .out_0 (n_132));
  csa_tree_gte_63_16_group_26 csa_tree_gte_63_16_groupi(.in_0
       ({UNCONNECTED_HIER_Z1, A}), .in_1 ({UNCONNECTED_HIER_Z2, B}),
       .out_0 (n_133));
  SDFFRHQX1 \F_reg[3] (.RN (n_4), .CK (clk), .D (n_130), .SI (F[2]),
       .SE (DFT_sen), .Q (F[3]));
  OAI221X1 g2125(.A0 (n_35), .A1 (n_107), .B0 (n_53), .B1 (n_48), .C0
       (n_129), .Y (n_130));
  AOI31X1 g2126(.A0 (B[3]), .A1 (A[3]), .A2 (n_57), .B0 (n_128), .Y
       (n_129));
  SDFFRHQX1 \F_reg[2] (.RN (n_4), .CK (clk), .D (n_127), .SI (F[1]),
       .SE (DFT_sen), .Q (F[2]));
  OAI211X1 g2128(.A0 (n_41), .A1 (n_49), .B0 (n_111), .C0 (n_126), .Y
       (n_128));
  OR4X1 g2129(.A (n_83), .B (n_115), .C (n_110), .D (n_123), .Y
       (n_127));
  SDFFRHQX1 \F_reg[1] (.RN (n_4), .CK (clk), .D (n_124), .SI (F[0]),
       .SE (DFT_sen), .Q (F[1]));
  SDFFRHQX1 Cout_reg(.RN (n_4), .CK (clk), .D (n_125), .SI (DFT_sdi),
       .SE (DFT_sen), .Q (Cout));
  AOI211XL g2132(.A0 (A[3]), .A1 (n_113), .B0 (n_114), .C0 (n_122), .Y
       (n_126));
  OAI211X1 g2133(.A0 (n_44), .A1 (n_133), .B0 (n_73), .C0 (n_121), .Y
       (n_125));
  OR4X1 g2134(.A (n_69), .B (n_93), .C (n_112), .D (n_119), .Y (n_124));
  SDFFRHQX1 \F_reg[0] (.RN (n_4), .CK (clk), .D (n_120), .SI (Cout),
       .SE (DFT_sen), .Q (F[0]));
  OAI221X1 g2136(.A0 (n_47), .A1 (n_108), .B0 (n_64), .B1 (n_59), .C0
       (n_103), .Y (n_123));
  OAI22X1 g2137(.A0 (n_47), .A1 (n_116), .B0 (n_64), .B1 (n_91), .Y
       (n_122));
  AOI2BB1X1 g2138(.A0N (n_35), .A1N (n_96), .B0 (n_117), .Y (n_121));
  OAI211X1 g2139(.A0 (n_1), .A1 (n_79), .B0 (n_77), .C0 (n_118), .Y
       (n_120));
  OAI222X1 g2140(.A0 (n_71), .A1 (n_63), .B0 (n_28), .B1 (n_106), .C0
       (n_29), .C1 (n_95), .Y (n_119));
  AOI221X1 g2141(.A0 (n_1), .A1 (n_97), .B0 (n_30), .B1 (n_81), .C0
       (n_76), .Y (n_118));
  OAI211X1 g2142(.A0 (n_64), .A1 (n_132), .B0 (n_109), .C0 (n_105), .Y
       (n_117));
  XNOR2X1 g2143(.A (n_104), .B (n_88), .Y (n_116));
  OAI221X1 g2144(.A0 (n_9), .A1 (n_49), .B0 (n_11), .B1 (n_58), .C0
       (n_101), .Y (n_115));
  AOI21X1 g2145(.A0 (n_72), .A1 (n_100), .B0 (A[3]), .Y (n_114));
  OAI221X1 g2146(.A0 (n_87), .A1 (n_45), .B0 (n_86), .B1 (n_37), .C0
       (n_79), .Y (n_113));
  OAI221X1 g2147(.A0 (n_28), .A1 (n_48), .B0 (n_7), .B1 (n_49), .C0
       (n_102), .Y (n_112));
  OA22X1 g2148(.A0 (n_44), .A1 (n_90), .B0 (n_98), .B1 (n_45), .Y
       (n_111));
  OAI22X1 g2149(.A0 (n_35), .A1 (n_92), .B0 (n_85), .B1 (n_45), .Y
       (n_110));
  OA22X1 g2150(.A0 (n_99), .A1 (n_45), .B0 (n_3), .B1 (n_100), .Y
       (n_109));
  XNOR2X1 g2151(.A (n_80), .B (n_89), .Y (n_108));
  XNOR2X1 g2152(.A (n_65), .B (n_94), .Y (n_107));
  AOI22X1 g2153(.A0 (n_19), .A1 (n_82), .B0 (n_18), .B1 (n_43), .Y
       (n_106));
  OAI211X1 g2154(.A0 (n_14), .A1 (n_61), .B0 (n_25), .C0 (n_46), .Y
       (n_105));
  OAI2BB1X1 g2155(.A0N (A[0]), .A1N (n_80), .B0 (n_75), .Y (n_104));
  AOI22X1 g2156(.A0 (n_43), .A1 (n_60), .B0 (n_84), .B1 (n_36), .Y
       (n_103));
  AOI22X1 g2157(.A0 (A[1]), .A1 (n_78), .B0 (n_55), .B1 (n_36), .Y
       (n_102));
  OA22X1 g2158(.A0 (n_2), .A1 (n_79), .B0 (n_27), .B1 (n_48), .Y
       (n_101));
  INVX1 g2159(.A (n_98), .Y (n_99));
  NAND3X1 g2160(.A (n_72), .B (n_37), .C (n_45), .Y (n_97));
  AOI21X1 g2161(.A0 (n_25), .A1 (n_62), .B0 (n_14), .Y (n_96));
  OA22X1 g2162(.A0 (n_18), .A1 (n_56), .B0 (n_19), .B1 (n_64), .Y
       (n_95));
  NAND2X1 g2163(.A (n_86), .B (n_36), .Y (n_100));
  NAND2X1 g2164(.A (n_3), .B (n_87), .Y (n_98));
  OAI22X1 g2165(.A0 (n_50), .A1 (n_74), .B0 (n_16), .B1 (n_26), .Y
       (n_94));
  OAI22X1 g2166(.A0 (n_55), .A1 (n_45), .B0 (A[1]), .B1 (n_72), .Y
       (n_93));
  CLKXOR2X1 g2167(.A (n_50), .B (n_75), .Y (n_92));
  XNOR2X1 g2168(.A (n_54), .B (n_67), .Y (n_91));
  XNOR2X1 g2169(.A (n_54), .B (n_66), .Y (n_90));
  XNOR2X1 g2170(.A (A[0]), .B (n_75), .Y (n_89));
  CLKXOR2X1 g2171(.A (n_74), .B (n_65), .Y (n_88));
  ADDHX1 g2172(.A (n_2), .B (n_6), .CO (n_87), .S (n_85));
  ADDHX1 g2173(.A (A[2]), .B (n_42), .CO (n_86), .S (n_84));
  NOR2X1 g2174(.A (A[2]), .B (n_72), .Y (n_83));
  NAND2X1 g2175(.A (n_35), .B (n_64), .Y (n_82));
  NAND2X1 g2176(.A (n_47), .B (n_64), .Y (n_81));
  INVX1 g2177(.A (n_78), .Y (n_79));
  NAND2BX1 g2178(.AN (n_30), .B (n_68), .Y (n_77));
  OAI22X1 g2179(.A0 (n_19), .A1 (n_49), .B0 (n_18), .B1 (n_58), .Y
       (n_76));
  NOR2BX1 g2180(.AN (n_18), .B (n_70), .Y (n_80));
  OAI21X1 g2181(.A0 (n_40), .A1 (n_31), .B0 (n_73), .Y (n_78));
  ADDHX1 g2182(.A (n_16), .B (n_26), .CO (n_74), .S (n_75));
  ADDHX1 g2183(.A (A[0]), .B (n_29), .CO (n_70), .S (n_71));
  NOR2X1 g2184(.A (n_22), .B (n_58), .Y (n_69));
  NAND3X1 g2185(.A (n_35), .B (n_44), .C (n_48), .Y (n_68));
  OAI21X1 g2186(.A0 (n_9), .A1 (n_38), .B0 (n_11), .Y (n_67));
  OAI21X1 g2187(.A0 (n_9), .A1 (n_39), .B0 (n_11), .Y (n_66));
  NAND2BX1 g2188(.AN (S[2]), .B (n_57), .Y (n_73));
  NAND3BX1 g2189(.AN (S[1]), .B (S[2]), .C (n_52), .Y (n_72));
  OA22X1 g2190(.A0 (n_19), .A1 (n_35), .B0 (n_17), .B1 (n_47), .Y
       (n_63));
  OAI21X1 g2191(.A0 (n_24), .A1 (n_33), .B0 (n_20), .Y (n_62));
  AOI21X1 g2192(.A0 (n_20), .A1 (n_34), .B0 (n_24), .Y (n_61));
  XNOR2X1 g2193(.A (n_39), .B (n_26), .Y (n_60));
  XNOR2X1 g2194(.A (n_38), .B (n_27), .Y (n_59));
  XNOR2X1 g2195(.A (n_21), .B (n_54), .Y (n_65));
  OR3X1 g2196(.A (S[2]), .B (S[1]), .C (n_51), .Y (n_64));
  INVX1 g2197(.A (n_58), .Y (n_57));
  NAND2X1 g2198(.A (S[1]), .B (n_52), .Y (n_58));
  NOR2X1 g2199(.A (n_46), .B (n_43), .Y (n_56));
  INVX1 g2200(.A (n_54), .Y (n_53));
  INVX1 g2201(.A (n_52), .Y (n_51));
  INVX1 g2202(.A (n_47), .Y (n_46));
  INVX1 g2203(.A (n_44), .Y (n_43));
  ADDHX1 g2204(.A (A[0]), .B (A[1]), .CO (n_42), .S (n_55));
  ADDHX1 g2205(.A (n_3), .B (n_5), .CO (n_41), .S (n_54));
  ADDHX1 g2206(.A (Cin), .B (S[0]), .CO (n_52), .S (n_40));
  NAND2X1 g2207(.A (n_23), .B (n_28), .Y (n_50));
  OR2X1 g2208(.A (S[1]), .B (n_0), .Y (n_49));
  NAND2BX1 g2209(.AN (n_0), .B (S[1]), .Y (n_48));
  NAND2BX1 g2210(.AN (n_31), .B (S[0]), .Y (n_47));
  NAND2BX1 g2211(.AN (S[1]), .B (n_32), .Y (n_45));
  NAND2X1 g2212(.A (S[1]), .B (n_32), .Y (n_44));
  INVX1 g2213(.A (n_37), .Y (n_36));
  OAI2BB1X1 g2214(.A0N (n_13), .A1N (n_16), .B0 (n_10), .Y (n_34));
  AOI21X1 g2215(.A0 (n_10), .A1 (n_23), .B0 (n_15), .Y (n_33));
  OA21X1 g2216(.A0 (n_7), .A1 (n_18), .B0 (n_22), .Y (n_39));
  OA21X1 g2217(.A0 (n_19), .A1 (n_7), .B0 (n_22), .Y (n_38));
  NAND3BXL g2218(.AN (S[0]), .B (S[1]), .C (n_8), .Y (n_37));
  NAND3X2 g2219(.A (S[0]), .B (S[1]), .C (n_8), .Y (n_35));
  NOR2X1 g2220(.A (S[2]), .B (n_12), .Y (n_32));
  NAND2BX1 g2222(.AN (S[1]), .B (n_8), .Y (n_31));
  INVX1 g2223(.A (n_29), .Y (n_28));
  INVX1 g2224(.A (n_27), .Y (n_26));
  AND2X1 g2225(.A (n_23), .B (n_13), .Y (n_30));
  NAND2X1 g2226(.A (n_16), .B (n_10), .Y (n_29));
  NOR2X1 g2227(.A (n_21), .B (n_24), .Y (n_27));
  INVX1 g2228(.A (n_21), .Y (n_20));
  INVX1 g2229(.A (n_18), .Y (n_17));
  INVX1 g2230(.A (n_16), .Y (n_15));
  NAND2X1 g2231(.A (B[3]), .B (n_3), .Y (n_25));
  NOR2BX1 g2232(.AN (B[2]), .B (A[2]), .Y (n_24));
  NAND2X1 g2233(.A (B[0]), .B (n_1), .Y (n_23));
  NAND2X1 g2234(.A (B[1]), .B (A[1]), .Y (n_22));
  NOR2X1 g2235(.A (B[2]), .B (n_2), .Y (n_21));
  NOR2X1 g2236(.A (B[0]), .B (A[0]), .Y (n_19));
  NAND2X1 g2237(.A (B[0]), .B (A[0]), .Y (n_18));
  NAND2BX1 g2238(.AN (B[1]), .B (A[1]), .Y (n_16));
  NOR2X1 g2240(.A (B[3]), .B (n_3), .Y (n_14));
  NAND2BX1 g2241(.AN (B[0]), .B (A[0]), .Y (n_13));
  NAND2BX1 g2242(.AN (S[0]), .B (Cin), .Y (n_12));
  NOR2X1 g2243(.A (A[0]), .B (A[1]), .Y (n_6));
  NAND2X1 g2244(.A (B[2]), .B (A[2]), .Y (n_11));
  NAND2BX1 g2245(.AN (A[1]), .B (B[1]), .Y (n_10));
  NOR2X1 g2246(.A (B[2]), .B (A[2]), .Y (n_9));
  NOR2X1 g2247(.A (Cin), .B (S[2]), .Y (n_8));
  NOR2X1 g2248(.A (B[1]), .B (A[1]), .Y (n_7));
  INVX1 g2249(.A (B[3]), .Y (n_5));
  INVX1 g2250(.A (reset), .Y (n_4));
  INVX1 g2251(.A (A[3]), .Y (n_3));
  INVX1 g2252(.A (A[2]), .Y (n_2));
  INVX1 g2253(.A (A[0]), .Y (n_1));
  NAND2BX1 g2(.AN (n_12), .B (S[2]), .Y (n_0));
endmodule

module SHIFTER(F, H, O);
  input [3:0] F;
  input [1:0] H;
  output [3:0] O;
  wire [3:0] F;
  wire [1:0] H;
  wire [3:0] O;
  wire n_0, n_1, n_2, n_3, n_5;
  OAI2BB1X1 g142(.A0N (F[3]), .A1N (n_1), .B0 (n_3), .Y (O[2]));
  OAI2BB1X1 g143(.A0N (F[0]), .A1N (n_2), .B0 (n_5), .Y (O[1]));
  AO22X1 g144(.A0 (F[3]), .A1 (n_0), .B0 (F[2]), .B1 (n_2), .Y (O[3]));
  AOI22X1 g145(.A0 (F[1]), .A1 (n_0), .B0 (F[2]), .B1 (n_1), .Y (n_5));
  AO22X1 g146(.A0 (F[0]), .A1 (n_0), .B0 (F[1]), .B1 (n_1), .Y (O[0]));
  AOI22X1 g147(.A0 (F[2]), .A1 (n_0), .B0 (F[1]), .B1 (n_2), .Y (n_3));
  NOR2BX1 g148(.AN (H[1]), .B (H[0]), .Y (n_2));
  NOR2BX1 g149(.AN (H[0]), .B (H[1]), .Y (n_1));
  NOR2X1 g150(.A (H[0]), .B (H[1]), .Y (n_0));
endmodule

module TOP(A, B, S, Cin, clk, reset, H, Cout, O, scan_in_1, scan_out_1,
     scan_enable);
  input [3:0] A, B;
  input [2:0] S;
  input Cin, clk, reset;
  input [1:0] H;
  output Cout;
  output [3:0] O;
  inout scan_in_1, scan_out_1, scan_enable;
  wire [3:0] A, B;
  wire [2:0] S;
  wire Cin, clk, reset;
  wire [1:0] H;
  wire Cout;
  wire [3:0] O;
  wire scan_in_1, scan_out_1, scan_enable;
  wire [3:0] W;
  ALU alu_inst(.A (A), .B (B), .S (S), .Cin (Cin), .clk (clk), .reset
       (reset), .F ({scan_out_1, W[2:0]}), .Cout (Cout), .DFT_sdi
       (scan_in_1), .DFT_sen (scan_enable));
  SHIFTER shifter_inst(.F ({scan_out_1, W[2:0]}), .H (H), .O (O));
endmodule

